source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/VoIPGRID/PrivatePodSpecs-iOS.git'

platform :ios, '9.0'
#use_frameworks! #!! Do not enable, causes an error about "target has transitive dependencies that include static binaries.... "

def pods_for_all_targets
    pod 'Vialer-pjsip-iOS'
    # To force the use of a specific version of the Vialer-pjsip pod, you can specify a branch as below:
    # pod 'Vialer-pjsip-iOS', :git => 'https://github.com/VoIPGRID/Vialer-pjsip-iOS.git', :branch => 'feature/PJSIP-2.5'
    pod 'VialerSIPLib-iOS', :path => '../'
end

target 'VialerSIPLib_Example' do
    pods_for_all_targets
    pod 'HDLumberjackLogFormatter', :git => 'https://hd-apps@bitbucket.org/hd-apps/hdlumberjacklogformatter.git'
end

target 'VialerSIPLib_Tests' do
    pods_for_all_targets
    pod 'OCMock'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
	        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PJ_AUTOCONF=1'
        end
    end
end
